relayer:
  certificate:
    filepath: "keys/private/tmpcert"
certificates:
  signing:
    root:
      o: "pauwels"
      ou: "signing"
      cn: "root"
      expires_in: 365
      filepath: "certs/root-signing.pem"
  encryption:
    tls:
      o: "pauwels"
      ou: "encryption"
      cn: "laptop"
      expires_in: 365
      filepath: "certs/client-tls.pem"
storage:
  url: http://localhost:8081
keys:
  encryption:
    symmetric:
      default:
        path: ".keys.encryption.symmetric.default."
        builder:
          t: "Key"
          c:
            t: "Symmetric"
            c:
              t: "SodiumOxide"
              c: {}
        value:
          t: "Unsealed"
          c:
            bytes:
              t: "Fs"
              c:
                path:
                  path: "keys/private/.keys.encryption.symmetric.default."
                  stem: ".keys.encryption.symmetric.default."
    asymmetric:
      tls:
        path: ".keys.encryption.asymmetric.tls."
        builder:
          t: "Key"
          c:
            t: "Asymmetric"
            c:
              t: "Secret"
              c:
                t: "SodiumOxideCurve25519"
                c: {}
        value:
          t: "Unsealed"
          c:
            bytes:
              t: "Fs"
              c:
                path:
                  path: "keys/private/.keys.encryption.asymmetric.tls."
                  stem: ".keys.encryption.asymmetric.tls."
  signing:
    root:
      path: ".keys.signing.root."
      builder:
        t: "Key"
        c:
          t: "Asymmetric"
          c:
            t: "Secret"
            c:
              t: "SodiumOxideEd25519"
              c: {}
      value:
        t: "Unsealed"
        c:
          bytes:
            t: "Fs"
            c:
              path:
                path: "keys/private/.keys.signing.root."
                stem: ".keys.signing.root."
