relayer:
  certificate:
    filepath: "keys/private/client-tls.p12.pem"
certificates:
  signing:
    root:
      o: "pauwels"
      ou: "signing"
      cn: "root"
      expires_in: 365
      filepath: "certs/root-signing.pem"
    tls:
      o: "pauwels"
      ou: "tls"
      cn: "laptop"
      expires_in: 365
      filepath: "certs/client-tls.pem"
    storertls:
      o: "pauwels"
      ou: "tls"
      cn: "localhost"
      expires_in: 365
      filepath: "certs/storer-tls.pem"
storage:
  url: https://localhost:8081
  tls:
    client:
      pkcs12:
        filepath: "keys/private/client-tls.p12.pem"
    server:
      ca:
        filepath: "certs/root-signing.pem"
keys:
  encryption:
    symmetric:
      default:
        path: ".keys.encryption.symmetric.default."
        builder:
          t: "Key"
          c:
            t: "Symmetric"
            c:
              t: "SodiumOxide"
              c: {}
        value:
          t: "Unsealed"
          c:
            bytes:
              t: "Fs"
              c:
                path:
                  path: "keys/private/.keys.encryption.symmetric.default."
                  stem: ".keys.encryption.symmetric.default."
  signing:
    root:
      path: ".keys.signing.root."
      builder:
        t: "Key"
        c:
          t: "Asymmetric"
          c:
            t: "Secret"
            c:
              t: "SodiumOxideEd25519"
              c: {}
      value:
        t: "Unsealed"
        c:
          bytes:
            t: "Fs"
            c:
              path:
                path: "keys/private/.keys.signing.root."
                stem: ".keys.signing.root."
    tls:
      path: ".keys.signing.tls."
      builder:
        t: "Key"
        c:
          t: "Asymmetric"
          c:
            t: "Secret"
            c:
              t: "SodiumOxideEd25519"
              c: {}
      value:
        t: "Unsealed"
        c:
          bytes:
            t: "Fs"
            c:
              path:
                path: "keys/private/.keys.signing.tls."
                stem: ".keys.signing.tls."
    storertls:
      path: ".storer.keys.signing.tls."
      builder:
        t: "Key"
        c:
          t: "Asymmetric"
          c:
            t: "Secret"
            c:
              t: "SodiumOxideEd25519"
              c: {}
      value:
        t: "Unsealed"
        c:
          bytes:
            t: "Fs"
            c:
              path:
                path: "keys/private/.storer.keys.signing.tls."
                stem: ".storer.keys.signing.tls."
